# Generated by Django 3.1.1 on 2021-09-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CnsrPac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admianemia',
            name='fechaAdmi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presanemia',
            name='fechaPres',
            field=models.DateField(),
        ),
    ]
