# Generated by Django 3.1.1 on 2021-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CnsrPac', '0002_auto_20210917_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='admianemia',
            name='dosisHieAdmi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admianemia',
            name='medHieAdmi',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presanemia',
            name='dosisHiePres',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presanemia',
            name='medHiePres',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
