# Generated by Django 3.1.1 on 2021-09-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CnsrPac', '0004_auto_20210922_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='exclusionAnemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaExclu', models.DateField()),
                ('razonExclu', models.CharField(max_length=30)),
                ('ObservaExclu', models.CharField(max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CnsrPac.paciente')),
            ],
        ),
    ]
