# Generated by Django 3.1.1 on 2021-08-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebadatos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dato', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pruebaDatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solexalab',
            fields=[
                ('soleqporicenasicod', models.CharField(db_column='SolEqpOriCenAsiCod', max_length=1, primary_key=True, serialize=False)),
                ('soleqpcenasicod', models.CharField(db_column='SolEqpCenAsiCod', max_length=3)),
                ('soleqptipexacod', models.CharField(db_column='SolEqpTipExaCod', max_length=1)),
                ('soleqpexanum', models.DecimalField(db_column='SolEqpExaNum', decimal_places=0, max_digits=10)),
                ('soleqpproeqlcod', models.CharField(blank=True, db_column='SolEqpProEqLCod', max_length=2, null=True)),
                ('soleqpsolexafec', models.CharField(blank=True, db_column='SolEqpSolExaFec', max_length=10, null=True)),
                ('soleqpordcod', models.CharField(blank=True, db_column='SolEqpOrdCod', max_length=8, null=True)),
                ('soleqptipdocidenpercod', models.CharField(blank=True, db_column='SolEqpTipDocIdenPerCod', max_length=1, null=True)),
                ('soleqpperasisdociden', models.CharField(blank=True, db_column='SolEqpPerAsisDocIden', max_length=10, null=True)),
                ('soleqpprocolcod', models.CharField(blank=True, db_column='SolEqpProColCod', max_length=5, null=True)),
                ('soleqpproapepat', models.CharField(blank=True, db_column='SolEqpProApePat', max_length=30, null=True)),
                ('soleqpproapemat', models.CharField(blank=True, db_column='SolEqpProApeMat', max_length=30, null=True)),
                ('soleqpproprinom', models.CharField(blank=True, db_column='SolEqpProPriNom', max_length=20, null=True)),
                ('soleqpprosegnom', models.CharField(blank=True, db_column='SolEqpProSegNom', max_length=20, null=True)),
                ('soleqppactipdocidencod', models.CharField(blank=True, db_column='SolEqpPacTipDocIdenCod', max_length=1, null=True)),
                ('soleqppacdocidennum', models.CharField(blank=True, db_column='SolEqpPacDocIdenNum', max_length=15, null=True)),
                ('soleqppacapepat', models.CharField(blank=True, db_column='SolEqpPacApePat', max_length=20, null=True)),
                ('soleqppacapemat', models.CharField(blank=True, db_column='SolEqpPacApeMat', max_length=20, null=True)),
                ('soleqppacprinom', models.CharField(blank=True, db_column='SolEqpPacPriNom', max_length=10, null=True)),
                ('soleqppacsegnom', models.CharField(blank=True, db_column='SolEqpPacSegNom', max_length=10, null=True)),
                ('soleqppachisclinum', models.DecimalField(blank=True, db_column='SolEqpPacHisCliNum', decimal_places=0, max_digits=10, null=True)),
                ('soleqppacautcod', models.CharField(blank=True, db_column='SolEqpPacAutCod', max_length=15, null=True)),
                ('soleqppacsexcod', models.CharField(blank=True, db_column='SolEqpPacSexCod', max_length=1, null=True)),
                ('soleqppacnacfec', models.CharField(blank=True, db_column='SolEqpPacNacFec', max_length=10, null=True)),
                ('soleqppacedad', models.DecimalField(blank=True, db_column='SolEqpPacEdad', decimal_places=0, max_digits=3, null=True)),
                ('soleqppacestcivcod', models.CharField(blank=True, db_column='SolEqpPacEstCivCod', max_length=1, null=True)),
                ('soleqppactelfij', models.CharField(blank=True, db_column='SolEqpPacTelFij', max_length=10, null=True)),
                ('soleqppactelcel', models.CharField(blank=True, db_column='SolEqpPacTelCel', max_length=10, null=True)),
                ('soleqppacfamtel', models.CharField(blank=True, db_column='SolEqpPacFamTel', max_length=10, null=True)),
                ('soleqparehoscod', models.CharField(blank=True, db_column='SolEqpAreHosCod', max_length=2, null=True)),
                ('soleqpserhoscod', models.CharField(blank=True, db_column='SolEqpSerHosCod', max_length=3, null=True)),
                ('soleqpemecod', models.CharField(blank=True, db_column='SolEqpEmeCod', max_length=2, null=True)),
                ('soleqptopemecod', models.CharField(blank=True, db_column='SolEqpTopEmeCod', max_length=2, null=True)),
                ('soleqpestenfcod', models.CharField(blank=True, db_column='SolEqpEstEnfCod', max_length=2, null=True)),
                ('soleqphabcod', models.CharField(blank=True, db_column='SolEqpHabCod', max_length=4, null=True)),
                ('soleqpcamcod', models.CharField(blank=True, db_column='SolEqpCamCod', max_length=5, null=True)),
                ('soleqpcenquicod', models.CharField(blank=True, db_column='SolEqpCenQuiCod', max_length=2, null=True)),
                ('soleqpsalopecod', models.CharField(blank=True, db_column='SolEqpSalOpeCod', max_length=2, null=True)),
                ('soleqpsiscod', models.CharField(blank=True, db_column='SolEqpSisCod', max_length=1, null=True)),
                ('soleqpdirip', models.CharField(blank=True, db_column='SolEqpDirIp', max_length=15, null=True)),
                ('soleqpusucrecod', models.CharField(blank=True, db_column='SolEqpUsuCreCod', max_length=10, null=True)),
                ('soleqpcrefec', models.CharField(blank=True, db_column='SolEqpCreFec', max_length=20, null=True)),
                ('solflgexito', models.CharField(blank=True, db_column='SolFlgExito', max_length=1, null=True)),
                ('solflgtransferencia', models.CharField(blank=True, db_column='SolFlgTransferencia', max_length=1, null=True)),
            ],
            options={
                'db_table': 'SolExaLab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solexalabcps',
            fields=[
                ('soleqporicenasicod', models.OneToOneField(db_column='SolEqpOriCenAsiCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServLisLab.solexalab')),
                ('soleqpcenasicod', models.CharField(db_column='SolEqpCenAsiCod', max_length=3)),
                ('soleqptipexacod', models.CharField(db_column='SolEqpTipExaCod', max_length=1)),
                ('soleqpexanum', models.DecimalField(db_column='SolEqpExaNum', decimal_places=0, max_digits=10)),
                ('soleqpcpscod', models.CharField(db_column='SolEqpCPSCod', max_length=5)),
                ('soleqpmuecod', models.CharField(db_column='SolEqpMueCod', max_length=3)),
                ('soleqpsedexacod', models.CharField(blank=True, db_column='SolEqpSedExaCod', max_length=2, null=True)),
                ('soleqpareexacod', models.CharField(blank=True, db_column='SolEqpAreExaCod', max_length=1, null=True)),
                ('reseqptomafec', models.CharField(blank=True, db_column='ResEqpTomaFec', max_length=10, null=True)),
                ('reseqptomahor', models.CharField(blank=True, db_column='ResEqpTomaHor', max_length=8, null=True)),
                ('soleqpprovcod', models.CharField(db_column='SolEqpProvCod', max_length=2)),
                ('soleqpflgtranseqp', models.CharField(blank=True, db_column='SolEqpFlgTransEqp', max_length=1, null=True)),
            ],
            options={
                'db_table': 'SolExaLabCPS',
                'managed': False,
            },
        ),
    ]
